apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  local-config.yaml: |
    schema_config:
      configs:
      - store: minio
        object_store:
          minio:
            bucket_name: "loki"
            endpoint: "http://minio-fs-svc:9000"
            access_key: "your-minio-access-key"
            secret_key: "your-minio-secret-key"
            expand-env: true
            insecure: true # Set to true if MinIO server uses self-signed certificates
