apiVersion: v1
kind: configMap
metadata: 
  name: promtail-configmpap
data:
  promtail.yaml: |
    server:
    http_listen_port: 9080
    grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
        - role: pod

